### ISSUE TITLE
Override default breakpoints when using media queries

### ISSUE THREAD

**Issue by tomhonig** [dragma/styled-bootstrap-grid#21]
Hi!

I having problem overriding the default breakpoints.
I'm using a `GridThemeProvider` and  ${media.desktop`...`} in my styled components.

Shouldn't it be props.theme.styledBootstrapGrid instead of props.theme.grid here?
https://github.com/dragma/styled-bootstrap-grid/blob/master/src/styled/media.js#L17

**Comment by dragma** [comment]
It seems you are right ! 
@damassi what do you think ?
Unfortunately, I have no time right now to test this, maybe tomorrow !

**Comment by damassi** [comment]
Hi @tomhonig - It should be `props.theme.grid.breakpoints`, as seen in our theme here: https://github.com/artsy/palette/blob/master/src/Theme.tsx#L94-L99.

What is the issue you're running into?

**Comment by dragma** [comment]
I'm on my phone, on a bus. I'll explain with more details later if you need it.

As far as I can see on my tiny screen, I think that you are right @tomhoning. We should read the `styledBootstrapGrid` object instead of the `grid` one.

The reason why the `props.theme.grid` object works in @damassi case is because, at the end, the `props.theme` object is shared between the `ThemeProvider` and the `GridThemeProvider`.

I will experience this tonight (or tomorrow) and I'll come back with more answers.

I confess, I don't need to use custom breakpoints on my different projects. :$

**Comment by tomhonig** [comment]
Thank you for your replies! 
Using `ThemeProvider` instead of the `GridThemeProvider` solved it:)
