### ISSUE TITLE
Example | Can't resolve './styled-bootstrap-grid'

### ISSUE THREAD

**Issue by nicolaschenet** [dragma/styled-bootstrap-grid#31]
Hey @dragma , I was just trying to run your example, but I'm facing a little technical issue. Here's what I get when I run `npm start` on the example

```
Module not found: Can't resolve './styled-bootstrap-grid'
```

**Node version:** v9.11.2
**NPM version:** v5.6.0

(The library is built)

**Comment by dragma** [comment]
I can't reproduce you bug. 
Are you absolutely sure that you've build the library before running the example ?
```
cd styled-bootstrap-grid
npm i
npm run build
cd example
yarn
yarn start
```

Thanks for your PR. I understand why you've done it that way, but I prefer the previous method, just because it is more convenient 
In your case, for each modification of the module, you'll have to reinstall the example dependencies, then relaunch the project, and I mostly use example for developing and debugging.

**Comment by nicolaschenet** [comment]
Just re-installed the whole thing. Did as you mentionned, and same error :) I'll ask someone else to clone and try to run the example

**Comment by dragma** [comment]
I installed your very version of node (v9.11.2).
I deleted the folders:
- ./node_moduler
- ./dist
- ./example/node_modules

Then I typed
- npm i
- npm run build
- cd example
- yarn
- yarn start

and.. BOOM, example page popped with no error. :)

I don't know what to say, 
If it doesn't work for you, I'll merge your PR.

**Comment by Fhou** [comment]
Hi @dragma,

I can also reproduce @nicolaschenet's bug.

And I can confirm his PR fixes the bug.

**Comment by dragma** [comment]
You are right. I made a shitty symbolic link that only works with my computers, that's why on each of my computers, the example works for me.
I'll merge your PR, I guess I'll have to fine another easy way to debug the module :)
